openapi: 3.0.0
info:
  title: Trail Management API
  description: API for managing trails, their location points and users.
  version: "1.0.0"
servers:
  - url: /api
paths:
  /login:
    post:
      summary: User login to obtain verification
      tags:
        - Authentication
      description: Authenticate users with their email and password using the external Authenticator API.
      operationId: authentication.User_Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address
                password:
                  type: string
                  description: The user's password
              required:
                - email
                - password
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  verified:
                    type: boolean
        "401":
          description: Invalid credentials
        "400":
          description: Missing email or password
        "500":
          description: Failed to authenticate with the external service
  /logout:
    post:
      summary: Logout the current user
      tags:
        - Authentication
      description: Logs out the currently logged-in user by clearing the session.
      operationId: authentication.User_Logout
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: No user was logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /users:
    get:
      summary: Retrieve all users
      tags:
        - Users
      operationId: api.user.get_users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    UserID:
                      type: integer
                    Email_Address:
                      type: string
                    User_Role:
                      type: string

  /trails:
    get:
      summary: Retrieve all trails
      tags:
        - Trails
      operationId: api.trail.get_trails
      responses:
        "200":
          description: A list of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    TrailID:
                      type: integer
                    Trail_Name:
                      type: string
                    Trail_Summary:
                      type: string
                    Trail_Description:
                      type: string
                    Trail_Difficulty:
                      type: string
                    Trail_Location:
                      type: string
                    Trail_Length:
                      type: number
                    Trail_Elevation_Gain:
                      type: number
                    Trail_Route_Type:
                      type: string
                    Trail_OwnerID:
                      type: integer
    post:
      summary: Create a new trail
      tags:
        - Trails
      operationId: api.trail.create_trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Trail_Name:
                  type: string
                Trail_Summary:
                  type: string
                Trail_Description:
                  type: string
                Trail_Difficulty:
                  type: string
                  enum: [Easy, Moderate, Hard]
                Trail_Location:
                  type: string
                Trail_Length:
                  type: number
                Trail_Elevation_Gain:
                  type: number
                Trail_Route_Type:
                  type: string
                  enum: [Circular, Out-and-back, Point-to-point]
                Trail_OwnerID:
                  type: integer
              required:
                - Trail_Name
                - Trail_Summary
                - Trail_Difficulty
                - Trail_Location
                - Trail_Length
                - Trail_OwnerID
      responses:
        "201":
          description: Trail created successfully
        "400":
          description: Missing required fields
  /trails/{trail_id}:
    get:
      summary: Retrieve a trail by ID with tags
      tags:
        - Trails
      operationId: api.trail.get_trail_by_id
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Trail details with tags
          content:
            application/json:
              schema:
                type: object
                properties:
                  TrailID:
                    type: integer
                  Trail_Name:
                    type: string
                  Trail_Summary:
                    type: string
                  Trail_Description:
                    type: string
                  Trail_Difficulty:
                    type: string
                  Trail_Location:
                    type: string
                  Trail_Length:
                    type: number
                  Trail_Elevation_Gain:
                    type: number
                  Trail_Route_Type:
                    type: string
                  Trail_OwnerID:
                    type: integer
                  Tags:
                    type: array
                    items:
                      type: object
                      properties:
                        TagID:
                          type: integer
                        Tag_Name:
                          type: string
                        Tag_Type:
                          type: string
        "404":
          description: Trail not found
    put:
      summary: Update a trail by ID
      tags:
        - Trails
      operationId: api.trail.update_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Trail_Name:
                  type: string
                Trail_Summary:
                  type: string
                Trail_Description:
                  type: string
                Trail_Difficulty:
                  type: string
                Trail_Location:
                  type: string
                Trail_Length:
                  type: number
                Trail_Elevation_Gain:
                  type: number
                Trail_Route_Type:
                  type: string
                Trail_OwnerID:
                  type: integer
      responses:
        "200":
          description: Trail updated successfully
        "404":
          description: Trail not found
    delete:
      summary: Delete a trail by ID
      tags:
        - Trails
      operationId: api.trail.delete_trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Trail deleted successfully
        "404":
          description: Trail not found
  /trails/{trail_id}/details:
    get:
      summary: Retrieve detailed information for a specific trail
      tags:
        - Trails
      operationId: api.trail.get_trail_details
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the trail to retrieve details for
      responses:
        "200":
          description: Detailed trail information including location points
          content:
            application/json:
              schema:
                type: object
                properties:
                  TrailID:
                    type: integer
                  Trail_Name:
                    type: string
                  Trail_Summary:
                    type: string
                  Trail_Description:
                    type: string
                  Trail_Difficulty:
                    type: string
                  Trail_Location:
                    type: string
                  Trail_Length:
                    type: number
                  Trail_Elevation_Gain:
                    type: number
                  Trail_Route_Type:
                    type: string
                  Trail_OwnerID:
                    type: integer
                  Location_Points:
                    type: array
                    items:
                      type: object
                      properties:
                        LocationID:
                          type: integer
                        Latitude:
                          type: number
                        Longitude:
                          type: number
                        Location_Description:
                          type: string
        "404":
          description: Trail not found

  /location_points:
    get:
      summary: Retrieve all location points
      tags:
        - Location points
      operationId: api.location_point.get_location_points
      responses:
        "200":
          description: List of location points
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Location_Point:
                      type: integer
                    Latitude:
                      type: number
                    Longitude:
                      type: number
                    Location_Description:
                      type: string
        "500":
          description: Internal server error
    post:
      summary: Add a location point
      tags:
        - Location points
      operationId: api.location_point.create_location_point
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                Latitude:
                  type: number
                Longitude:
                  type: number
                Location_description:
                  type: string
              required:
                - Latitude
                - Longitude
      responses:
        "202":
          description: Location point added successfully
        "400":
          description: Missing required fields
  /location_points/{location_point_id}:
    get:
      summary: Retrieve a specific location point by ID
      tags:
        - Location points
      operationId: api.location_point.get_location_point_by_id
      parameters:
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the location point to retrieve
      responses:
        "200":
          description: Details of the location point
          content:
            application/json:
              schema:
                type: object
                properties:
                  Location_Point:
                    type: integer
                  Latitude:
                    type: number
                  Longitude:
                    type: number
                  Location_Description:
                    type: string
        "404":
          description: Location point not found
        "500":
          description: Internal server error
    put:
      summary: Update an existing location point
      tags:
        - Location points
      operationId: api.location_point.update_location_point
      parameters:
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the location point to update
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                Latitude:
                  type: number
                Longitude:
                  type: number
                Location_Description:
                  type: string
      responses:
        "200":
          description: Location point updated successfully
        "400":
          description: Invalid input
        "404":
          description: Location point not found
        "500":
          description: Internal server error
    delete:
      summary: Delete a location point
      tags:
        - Location points
      operationId: api.location_point.delete_location_point
      parameters:
        - name: location_point_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the location point to delete
      responses:
        "204":
          description: Location point deleted successfully
        "404":
          description: Location point not found
        "500":
          description: Internal server error

  /tags:
    get:
      summary: Retrieve all tags
      tags:
        - Tags
      operationId: api.tag.get_tags
      responses:
        "200":
          description: Successfully retrieved all tags
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    TagID:
                      type: integer
                    Tag_Name:
                      type: string
                    Tag_Type:
                      type: string
        "500":
          description: Internal server error
    post:
      summary: Add a new tag
      tags:
        - Tags
      operationId: api.tag.create_tag
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                Tag_Name:
                  type: string
                Tag_Type:
                  type: string
                  enum: ["Trail Info", "Features", "Activities"]
              required: 
                - Tag_Name
                - Tag_Type
      responses:
        "202":
          description: Tag added successfully
        "400":
          description: Missing required fields
  /tags/{tag_id}:
    put:
      summary: Update an existing tag
      tags:
        - Tags
      operationId: api.tag.update_tag
      parameters:
        - name: tag_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the tag to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Tag_Name:
                  type: string
      responses:
        "200":
          description: Tag updated successfully
        "400":
          description: Invalid input
        "404":
          description: Tag not found
        "500":
          description: Internal server error
    delete:
      summary: Delete a tag
      tags:
        - Tags
      operationId: api.tag.delete_tag
      parameters:
        - name: tag_id
          in: path
          required: true
          schema:
            type: integer
          description: The Id of the tag to delete
      responses:
        "204":
          description: Tag deleted successfully
        "404":
          description: Tag not found
        "500":
          description: Internal server error
