openapi: 3.0.0
info:
  title: Trail Management API
  description: API for managing trails, users, and location points.
  version: "1.0.0"
servers:
  - url: /api
paths:
  /login:
    post:
      summary: User login to obtain verification
      description: Authenticate users with their email and password using the external Authenticator API.
      operationId: authentication.User_Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address
                password:
                  type: string
                  description: The user's password
              required:
                - email
                - password
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  verified:
                    type: boolean
        "401":
          description: Invalid credentials
        "400":
          description: Missing email or password
        "500":
          description: Failed to authenticate with the external service

  /users:
    get:
      summary: Retrieve all users
      operationId: api.user.get_users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    UserID:
                      type: integer
                    Email_Address:
                      type: string
                    User_Role:
                      type: string

  /trails:
    get:
      summary: Retrieve all trails
      operationId: api.trail.get_trails
      responses:
        "200":
          description: A list of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    TrailID:
                      type: integer
                    Trail_Name:
                      type: string
                    Trail_Summary:
                      type: string
                    Trail_Description:
                      type: string
                    Trail_Difficulty:
                      type: string
                    Trail_Location:
                      type: string
                    Trail_Length:
                      type: number
                    Trail_Elevation_Gain:
                      type: number
                    Trail_Route_Type:
                      type: string
                    Trail_OwnerID:
                      type: integer
